services:
  # Production Angular app service
  ticketmaster:
    container_name: ticketmaster_app
    build:
      context: ./ticketmaster
      dockerfile: Dockerfile
      args:
        - configuration=production
    image: ticketmaster_app:v1  
    ports:
      - 80:80
    depends_on:
      - server
      - elasticsearch
    networks:
      - ticketmaster-network

  # Production Node API service
  server:
    container_name: ticketmaster_api
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file:
      - ./server/.env  
    image: ticketmaster_api:v1
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://ticketmaster_db:27017/ticketmaster-db
      - CORS_ORIGIN=http://localhost:4200,http://localhost
      - SERVER_PORT=3000
    depends_on:
      - mongodb      
    networks:
      - ticketmaster-network

  # Mongodb service
  mongodb:
    image: mongo:latest
    container_name: ticketmaster_db
    ports:
      - 27017:27017
    restart: always
    networks:
      - ticketmaster-network
    volumes:
      - mongo_data:/data/db  

  # Elasticsearch service
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.0
    container_name: ticketmaster_elasticsearch
    environment: [
      'CLI_JAVA_OPTS=-Xms2g -Xmx2g',
      'bootstrap.memory_lock=true',
      'discovery.type=single-node',
      'xpack.security.enabled=false', 
      'xpack.security.enrollment.enabled=false'
      ]
    ports:
      - 9200:9200
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    deploy:    
      resources:
          limits:
            cpus: '2.0'
          reservations:
            cpus: '1.0'
    networks:
      - ticketmaster-network

  # Kibana service
  kibana:
    image: docker.elastic.co/kibana/kibana:8.14.0
    container_name: ticketmaster_kibana
    environment:
      XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY: d1a66dfd-c4d3-4a0a-8290-2abcb83ab3aa
    ports:
      - 5601:5601
    networks:
      - ticketmaster-network
    deploy:    
      resources:
          limits:
            cpus: '2.0'
          reservations:
            cpus: '1.0'

networks:
  ticketmaster-network:
    driver: bridge

volumes:
  mongo_data:

  