services:
  # Development Angular app service
  ticketmaster_dev:
    container_name: ticketmaster_app_dev
    build:
      context: ./ticketmaster
      dockerfile: Dockerfile.dev
      args:
        - configuration=development
    image: ticketmaster_app_dev:v1  
    ports:
      - 4200:4200
    environment:
      - NODE_ENV=development
    volumes:
      - ./ticketmaster:/app
      - /app/node_modules
    command: ng serve --host 0.0.0.0 --poll=2000
    depends_on:
      - server_dev
      - elasticsearch_dev
    networks:
      - ticketmaster-network-dev  

  # Development Node API service
  server_dev:
    container_name: ticketmaster_api_dev
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    env_file:
      - ./server/.env
    image: ticketmaster_api_dev:v1
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://ticketmaster_db_dev:27017/ticketmaster-db-dev
      - CORS_ORIGIN=http://localhost:4200,http://localhost
      - SERVER_PORT=3000
    volumes:
      - ./server:/usr/local/api
    command: npm run dev
    depends_on:
      - mongodb_dev      
    networks:
      - ticketmaster-network-dev

  # Mongodb service
  mongodb_dev:
    image: mongo:latest
    container_name: ticketmaster_db_dev
    ports:
      - 27017:27017
    restart: always
    networks:
      - ticketmaster-network-dev
    volumes:
      - mongo_data:/data/db  

  # Elasticsearch service
  elasticsearch_dev:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.1
    container_name: ticketmaster_elasticsearch_dev
    environment: [
      'CLI_JAVA_OPTS=-Xms2g -Xmx2g',
      'bootstrap.memory_lock=true',
      'discovery.type=single-node',
      'xpack.security.enabled=false', 
      'xpack.security.enrollment.enabled=false'
      ]
    ports:
      - 9200:9200
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    deploy:    
      resources:
          limits:
            cpus: '2.0'
          reservations:
            cpus: '1.0'
    networks:
      - ticketmaster-network-dev

  # Kibana service
  kibana_dev:
    image: docker.elastic.co/kibana/kibana:8.14.1
    container_name: ticketmaster_kibana_dev
    environment:
      XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY: d1a66dfd-c4d3-4a0a-8290-2abcb83ab3aa
    ports:
      - 5601:5601
    networks:
      - ticketmaster-network-dev
    deploy:    
      resources:
          limits:
            cpus: '2.0'
          reservations:
            cpus: '1.0'

networks:
  ticketmaster-network-dev:
    driver: bridge

volumes:
  mongo_data:
  node_modules: {}

  