# Stage 1: Build the Angular app
# Get the official Node.js image
FROM node:alpine AS development

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install
RUN npm install -g @angular/cli@8.3.29

# Copy the rest of the application code
COPY . .

# Expose port 4200
EXPOSE 4200

# Start the development app
CMD ["ng","serve","--host", "0.0.0.0", "--disableHostCheck"]

