# Get the official Node.js image
FROM node:alpine as development

# Set the working directory inside the container
WORKDIR /usr/local/api

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Install nodemon globally
RUN npm install -g nodemon

# Copy the rest of the application code
COPY . .

# Environment variables
ENV MODE_ENV=development

# Expose port 3000
EXPOSE 3000

# Start the server
CMD ["node", "server.js"]